module.exports = {
	_USER: "USER",
	_ADMIN: "ADMIN",
	_RESTAURANT: "RESTAURANT",
	_NOT_USER: "NOT USER",
	_NOT_ADMIN: "NOT ADMIN",
	_NOT_RESTAURANT: "NOT RESTAURANT",
	_NOT_TOKEN: "INCORRECT TOKEN"
};
